export PYTHONPATH:="."

lint-fix:
    poetry run isort .
    poetry run black .

lint-check:
    poetry run isort --check-only .
    poetry run black --check .

test-unit:
    poetry run python -m pytest tests/unit

serve-local:
    poetry run python -m app.main

train-local:
    poetry run python flows/training.py

train-sagemaker:
    poetry run python utils/launch_sagemaker.py

infer-huggingface:
    poetry run python -m backend.model.huggingface